import React, {useState, useEffect} from 'react'

import { Card, Form, Loader } from '../components'

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return (
      data.map((post) => <Card key={post._id} {...post} />)
    );
  }

  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};


const Home = () => {
  const [loading, setLoading] = useState(false);
  const [searchText, setSearchText] = useState(null);

  return (
    <section>
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">Images generated by people</h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Take a look at some stunning images generated by the ImgGenerator, you can also create images like these by accessing the CreateImage section</p>
      </div>

      <div className="mt-16" >
        <Form/>
      </div>

      <div>
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2>
                Showing results for <span>{searchText}</span>
              </h2>
            )}
            <div>
              {searchText ? (
                <RenderCards
                  data={[]}
                  title="No Search Results Found"
                />
              ) : (
                <RenderCards
                  data={[]}
                  title="No Posts Yet"
                />
              )}
            </div>
          </>
        )}
      </div>

    </section>
  )
}

export default Home